openapi: 3.0.1
info:
  title: Get user details
  description: User details by id
  version: 1.0.0
servers:
  - url: http://localhost
    description: Generated server url
paths:
  /public/v2/users/{id}:
    get:
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            minimum: 1
          description: The user ID
      operationId: get user
      responses:
        "200":
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/userDetails'
        "404":
          description: Not found
          content:
            application/json;charset=UTF-8:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example: { "message": "Resource not found" }
components:
  schemas:
    userDetails:
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
        email:
          type: string
        gender:
          type: string
        status:
          type: string
